In [1]:
# Import the dependencies.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
city_database = []

In [3]:
#  Using NumPy to create random figures
np.random.uniform(-90, 90, size=15)

array([-76.52415793,  76.50204967,   6.88277839,  -1.96509944,
        36.14891602, -69.45984932, -82.29174012, -72.29094388,
        69.40088984,  78.25921441,  42.14157641,  52.04777855,
       -55.5568558 ,  83.70395933,  60.12719746])

In [4]:
# Adding Timeit
%timeit np.random.uniform(-90, 90, size=15)

2.15 µs ± 27.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [5]:
# defining random latitudes
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = np.random.randint(-90, 90) + np.random.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes
# Call the function with 1500.
%timeit latitudes(15)

32.9 µs ± 385 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [6]:
# Create a set of random latitude and longitude combinations.
lats = np.random.uniform(low=-90.000, high=90.000, size=15)
lngs = np.random.uniform(low=-180.000, high=180.000, size=15)
lat_lngs = zip(lats, lngs)
lat_lngs

In [7]:
# Add the latitudes and longitudes to a list.
coordinates = list(lat_lngs)

In [8]:
# Import Citipy
from citipy import citipy
# Create a list for holding the cities.
cities = []
# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name

    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)
# Print the city count to confirm sufficient count.
len(cities)

15

In [9]:
cities

['sitka',
 'bethel',
 'yellowknife',
 'khatanga',
 'qasigiannguit',
 'ushuaia',
 'port elizabeth',
 'tutoia',
 'east london',
 'saint-philippe',
 'severo-kurilsk',
 'bambous virieux',
 'hermanus',
 'tautira',
 'mataura']

In [10]:
# Import the requests library.
import requests

# Import the API key.
from config import weather_api_key

# Import the time library and the datetime module from the datetime library 
import time
from datetime import datetime

In [11]:
# Starting URL for Weather Map API Call.
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key

In [12]:
# Print the beginning of the logging.
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters.
record_count = 1
set_count = 1

# Loop through all the cities in the list.
for i, city in enumerate(cities):

    # Group cities in sets of 50 for logging purposes.
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
        time.sleep(60)

    # Create endpoint URL with each city.
    city_url = url + "&q=" + city.replace(" ","+")

    # Log the URL, record, and set numbers and the city.
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    # Add 1 to the record count.
    record_count += 1

# Run an API request for each of the cities.
    try:
        # Parse the JSON and retrieve data.
        city_weather = requests.get(city_url).json()
        # Parse out the needed data.
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]    
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        # Convert the date to ISO standard.
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')
        # Append the city information into city_data list.
        city_database.append({"City": city.title(),
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Date": city_date})

# If an error is experienced, skip the city.
    except:
        print("City not found. Skipping...")
        pass

# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-----------------------------
Processing Record 1 of Set 1 | sitka
Processing Record 2 of Set 1 | bethel
Processing Record 3 of Set 1 | yellowknife
Processing Record 4 of Set 1 | khatanga
Processing Record 5 of Set 1 | qasigiannguit
Processing Record 6 of Set 1 | ushuaia
Processing Record 7 of Set 1 | port elizabeth
Processing Record 8 of Set 1 | tutoia
Processing Record 9 of Set 1 | east london
Processing Record 10 of Set 1 | saint-philippe
Processing Record 11 of Set 1 | severo-kurilsk
Processing Record 12 of Set 1 | bambous virieux
Processing Record 13 of Set 1 | hermanus
Processing Record 14 of Set 1 | tautira
Processing Record 15 of Set 1 | mataura
-----------------------------
Data Retrieval Complete
-----------------------------

In [13]:
city_database

[{'City': 'Sitka',
  'Lat': 57.0531,
  'Lng': -135.33,
  'Max Temp': 33.69,
  'Humidity': 60,
  'Cloudiness': 1,
  'Wind Speed': 5.75,
  'Country': 'US',
  'Date': '2022-01-02 20:22:58'},
 {'City': 'Bethel',
  'Lat': 41.3712,
  'Lng': -73.414,
  'Max Temp': 51.93,
  'Humidity': 89,
  'Cloudiness': 90,
  'Wind Speed': 1.01,
  'Country': 'US',
  'Date': '2022-01-02 20:22:58'},
 {'City': 'Yellowknife',
  'Lat': 62.456,
  'Lng': -114.3525,
  'Max Temp': -28.68,
  'Humidity': 75,
  'Cloudiness': 40,
  'Wind Speed': 10.36,
  'Country': 'CA',
  'Date': '2022-01-02 20:22:59'},
 {'City': 'Khatanga',
  'Lat': 71.9667,
  'Lng': 102.5,
  'Max Temp': -50.98,
  'Humidity': 99,
  'Cloudiness': 71,
  'Wind Speed': 3.29,
  'Country': 'RU',
  'Date': '2022-01-02 20:22:59'},
 {'City': 'Qasigiannguit',
  'Lat': 68.8193,
  'Lng': -51.1922,
  'Max Temp': 10.65,
  'Humidity': 77,
  'Cloudiness': 99,
  'Wind Speed': 5.86,
  'Country': 'GL',
  'Date': '2022-01-02 20:23:00'},
 {'City': 'Ushuaia',
  'Lat': -54.8,
  'Lng': -68.3,
  'Max Temp': 42.46,
  'Humidity': 61,
  'Cloudiness': 75,
  'Wind Speed': 35.68,
  'Country': 'AR',
  'Date': '2022-01-02 20:19:27'},
 {'City': 'Port Elizabeth',
  'Lat': -33.918,
  'Lng': 25.5701,
  'Max Temp': 63.1,
  'Humidity': 82,
  'Cloudiness': 0,
  'Wind Speed': 3.44,
  'Country': 'ZA',
  'Date': '2022-01-02 20:19:23'},
 {'City': 'Tutoia',
  'Lat': -2.7619,
  'Lng': -42.2744,
  'Max Temp': 84.18,
  'Humidity': 76,
  'Cloudiness': 92,
  'Wind Speed': 14.03,
  'Country': 'BR',
  'Date': '2022-01-02 20:23:02'},
 {'City': 'East London',
  'Lat': -33.0153,
  'Lng': 27.9116,
  'Max Temp': 67.1,
  'Humidity': 73,
  'Cloudiness': 100,
  'Wind Speed': 4.09,
  'Country': 'ZA',
  'Date': '2022-01-02 20:23:03'},
 {'City': 'Saint-Philippe',
  'Lat': -21.3585,
  'Lng': 55.7679,
  'Max Temp': 75.22,
  'Humidity': 80,
  'Cloudiness': 43,
  'Wind Speed': 11.36,
  'Country': 'RE',
  'Date': '2022-01-02 20:23:03'},
 {'City': 'Severo-Kurilsk',
  'Lat': 50.6789,
  'Lng': 156.125,
  'Max Temp': 25.99,
  'Humidity': 73,
  'Cloudiness': 93,
  'Wind Speed': 12.1,
  'Country': 'RU',
  'Date': '2022-01-02 20:23:04'},
 {'City': 'Bambous Virieux',
  'Lat': -20.3428,
  'Lng': 57.7575,
  'Max Temp': 76.21,
  'Humidity': 78,
  'Cloudiness': 20,
  'Wind Speed': 5.75,
  'Country': 'MU',
  'Date': '2022-01-02 20:23:04'},
 {'City': 'Hermanus',
  'Lat': -34.4187,
  'Lng': 19.2345,
  'Max Temp': 63.9,
  'Humidity': 73,
  'Cloudiness': 100,
  'Wind Speed': 5.06,
  'Country': 'ZA',
  'Date': '2022-01-02 20:20:37'},
 {'City': 'Tautira',
  'Lat': -17.7333,
  'Lng': -149.15,
  'Max Temp': 82.42,
  'Humidity': 88,
  'Cloudiness': 100,
  'Wind Speed': 10.09,
  'Country': 'PF',
  'Date': '2022-01-02 20:23:06'},
 {'City': 'Mataura',
  'Lat': -46.1927,
  'Lng': 168.8643,
  'Max Temp': 64.47,
  'Humidity': 63,
  'Cloudiness': 100,
  'Wind Speed': 1.23,
  'Country': 'NZ',
  'Date': '2022-01-02 20:23:06'}]

In [14]:
# Convert the array of dictionaries to a Pandas DataFrame.
city_data_df = pd.DataFrame(city_database)
city_data_df.head(10)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Sitka,57.0531,-135.3300,33.69,60,1,5.75,US,2022-01-02 20:22:58
1,Bethel,41.3712,-73.4140,51.93,89,90,1.01,US,2022-01-02 20:22:58
2,Yellowknife,62.4560,-114.3525,-28.68,75,40,10.36,CA,2022-01-02 20:22:59
3,Khatanga,71.9667,102.5000,-50.98,99,71,3.29,RU,2022-01-02 20:22:59
4,Qasigiannguit,68.8193,-51.1922,10.65,77,99,5.86,GL,2022-01-02 20:23:00
5,Ushuaia,-54.8000,-68.3000,42.46,61,75,35.68,AR,2022-01-02 20:19:27
6,Port Elizabeth,-33.9180,25.5701,63.10,82,0,3.44,ZA,2022-01-02 20:19:23
7,Tutoia,-2.7619,-42.2744,84.18,76,92,14.03,BR,2022-01-02 20:23:02
8,East London,-33.0153,27.9116,67.10,73,100,4.09,ZA,2022-01-02 20:23:03
9,Saint-Philippe,-21.3585,55.7679,75.22,80,43,11.36,RE,2022-01-02 20:23:03

In [15]:
# Create the output file (CSV).
output_data_file = "Weather_Database/WeatherPy_database.csv"
# Export the City_Data into a CSV.
city_data_df.to_csv(output_data_file, index_label="City_ID")